config/routes.rb
require 'sidekiq/web'

Chippd::Application.routes.draw do
  get "newsletter/index"

  get "newsletter/thanks"

  constraints(ApiConstraint) do
    scope :module => "api" do
      namespace :v1, :path => '1', :defaults => { :format => 'json' } do
        resource :customer, :only => [:create] do
          post 'sign_in'
        end
        get 'pages', :to => 'pages#index'
        get 'pages/not_found', :to => 'pages#not_found', :format => 'html'
        get 'pages/:key', :as => :page, :to => 'pages#show', :format => 'html'
        post 'pages/:key/leave', :as => :leave_page, :to => 'pages#leave'
        get 'pages/*junk', :to => 'pages#not_found', :format => 'html'
      end

      namespace :v2, :path => '2', :defaults => { :format => 'json' } do
        resource :customer, :only => [:create] do
          post 'sign_in'
        end
        get 'pages', :to => 'pages#index'
        get 'pages/not_found', :to => 'pages#not_found', :format => 'html'
        get 'pages/:key', :as => :page, :to => 'pages#show', :format => 'html'
        post 'pages/:key/leave', :as => :leave_page, :to => 'pages#leave'
        get 'pages/*junk', :to => 'pages#not_found', :format => 'html'
        resources :aws_signatures, only: :create, path: 'signatures'
        resources :mobile_playlists, only: :show, path: 'playlists'
      end
    end
  end

  devise_for :customers, :controllers => { :registrations => "customers/registrations", :sessions => "customers/sessions", :passwords => "customers/passwords" }
  devise_for :admins

  authenticate :admin do
    mount Sidekiq::Web => '/admin/sidekiq'
  end

  namespace :admin do
    resources :pages
    resources :product_collections, :except => [:show] do
      post 'sort', :on => :collection
      put 'toggle_visibility', :on => :member

      resources :products do
        post 'sort', :on => :collection
        put 'toggle_visibility', :on => :member
      end
    end

    resources :products, :only => nil do
      resources :images, :controller => "product_images" do
        post 'sort', :on => :collection
        put 'toggle_visibility', :on => :member
      end
    end

    resources :page_templates, :except => [:show] do
      post 'sort', :on => :collection
      put 'toggle_visibility', :on => :member
      resources :page_template_widgets, :path => 'widgets', :except => [:show] do
        post 'sort', :on => :collection
        put 'toggle_visibility', :on => :member
      end
    end
    resources :batches, :except => [:edit, :update, :destroy]
    resources :landing_pages do
      put 'toggle_visibility', :on => :member
      resources :steps, :controller => 'landing_page_steps' do
        post 'sort', :on => :collection
        put 'toggle_visibility', :on => :member
      end
      resources :images, :controller => 'landing_page_images' do
        post 'sort', :on => :collection
        put 'toggle_visibility', :on => :member
      end
    end
    root :to => "base#home"
    post 'markdown_preview', :to => "base#markdown_preview"

    resources :contact_requests, :only => [:index, :show, :destroy]
    resources :dollar_amount_discounts, :only => [:new, :edit, :create, :update]
    resources :percentage_discounts, :only => [:new, :edit, :create, :update]
    resources :discounts, :only => [:index, :toggle_visibility, :destroy] do
      put 'toggle_visibility', :on => :member
    end

    resources :shipping_options do
      post 'sort', :on => :collection
      put 'toggle_visibility', :on => :member
    end

    resources :chippd_product_types, :path => 'settings' do
      post 'sort', :on => :collection
      put 'toggle_visibility', :on => :member
    end

    resources :faqs do
      post 'sort', :on => :collection
      put 'toggle_visibility', :on => :member
    end

    resources :press_releases do
      post 'sort', :on => :collection
      put 'toggle_visibility', :on => :member
    end

    resources :contents

    resources :orders, :only => [:index, :edit, :update] do
      post 'search', :on => :collection
      get 'paid', :on => :collection
      get 'shipped', :on => :collection
      get 'canceled', :on => :collection
      put 'ship', :on => :member
      put 'cancel', :on => :member
      get 'invoice', :on => :member
    end

    resources :customers, :only => [:index, :show] do
      get 'line_items', :on => :collection
      get 'confirm', :on => :member
    end
  end

  namespace :store do
    root :to => "product_collections#index"
    get ':product_collection_id/products', :to => "products#index", :as => :products_by_product_collection
    get ':product_collection_id/:page_template_id/products', :to => "products#index_by_page_template", :as => :products_by_product_collection_and_page_template
    resources :products, :only => [:show] do
      resources :preorders, :only => [:create]
    end
    resource :order, :only => [:show, :update] do
      get 'cart', :as => :cart_for
      put 'cart/save', :action => 'save_cart', :as => :save_cart_for
      get 'customer_information', :as => :customer_information_for
      put 'customer_information/save', :action => 'save_customer_information', :as => :save_customer_information_for
      get 'review'
      put 'complete'
      get 'thank_you', :as => :thank_you_for_your
      get 'error', :as => :error_on_your
      resources :line_items, :only => [:create, :destroy]
      resource :applied_discount, :only => :destroy
    end
  end

  namespace :my_chippd, :path => 'my-chippd' do
    root :to => "base#index"
    resource :profile, :only => [:edit, :update, :destroy]
    resources :redemptions, :path => 'redeem', :only => [:index, :create] do
      get 'verify', :on => :collection
    end
    resources :pages, :only => [:index, :show, :edit, :update] do
      get 'chooser', :on => :collection, :as => :chooser_for
      put 'add_to_or_create', :on => :collection
      get 'example', :on => :collection
      post 'notify', :on => :member

      resources :memberships, :only => [:toggle_access] do
        put 'toggle_access', :on => :member
      end
      resources :auctions, :only => [] do
        post 'bid',   :on => :member
        get  'close', :on => :member
        get  'show',  :on => :collection
      end

      resources :sections do
        configatron.pages.valid_section_types.each do |section_type|
          get [:new, section_type].join('-'), :action => [:new, section_type].join('_'), :on => :collection, :as => [:new, section_type, :for].join('_')
        end
        delete 'reset', :on => :collection
        post 'sort', :on => :collection
        get 'download_vcard', :on => :member
        get 'content', :on => :member
        put 'toggle_visibility', :on => :member
      end
    end
  end
  post '/pusher/auth', to: 'my_chippd/base#pusher_auth'

  resources :rsvps, :only => [] do
    resources :responses, :only => [:index, :create, :update, :destroy], :controller => 'my_chippd/rsvp_responses'
  end

  get '/about-us', :to => "pages#about_us", :as => :about_us
  get '/go', :to => "pages#go"
  get '/how-it-works', :to => "pages#how_it_works", :as => :how_it_works
  get '/faq', :to => "pages#faq"
  get '/retailers', :to => "pages#retailers"
  get '/terms-of-service', :to => "pages#terms_of_service", :as => :terms_of_service
  get '/privacy-policy', :to => "pages#privacy_policy", :as => :privacy_policy
  get '/media-room', :to => "pages#media_room", :as => :media_room

  get '/newsletter', :to => "newsletter#index"
  get '/newsletter/thanks', :to => "newsletter#thanks"

  get '/widgets/baby', :to => "widgets#baby"
  get '/widgets/wedding', :to => "widgets#wedding"


  get '/contact-us', :to => "contact_requests#new", :as => :contact_us
  get '/contact-us/thank-you', :to => "contact_requests#thank_you", :as => :contact_request_thank_you
  resources :contact_requests, :only => [:new, :create], :path => 'contact-requests'

  get '/redeem', to: redirect('/activate')
  get '/activate', :to => "pages#redeem_tracking", as: 'redeem'

  resources :press_releases, :only => [:index, :show], :path => 'press'

  configatron.example_pages.each do |path, id|
    get "/examples/#{path.to_s.dasherize}", :to => "examples#show", :as => "#{path}_example", :id => id, :key => path
  end
  get "/ebolaandbeyond", :to => "my_chippd/auctions#show", :page_id => "54d274234c06fcc008000001"
  get "/ppaiexpoeast", :to => "examples#show", :page_id => "54f68261ee2cb7efa9000002", :as => "ppaiexpoeast_example", :id => '54f68261ee2cb7efa9000002', :key => 'ppaiexpoeast'
  get "/intro", :to => "examples#show", :page_id => "54f684a4ee2cb7efa9000003", :as => "intro_example", :id => '54f684a4ee2cb7efa9000003', :key => 'ppaiexpoeast'
  # get "/omaranddina", :to => "my_chippd/auctions#show", :page_id => "54eeb4b63672bcb7c0000028"
  get "/omaranddina", :to => "examples#show", :page_id => "5523084ff400bf85be000001", :as => "omaranddina_example", :id => '5523084ff400bf85be000001', :key => 'omaranddina'

  root :to => "pages#home"
  get '/:id', :to => 'landing_pages#show'
end

app/models/landing_page/landing_page.rb
class LandingPage
  include Mongoid::Document
  include Mongoid::Timestamps
  include HasVisibility

  embeds_many :images, :class_name => "LandingPageImage"
  embeds_many :steps, :class_name => "LandingPageStep"

  field :title, :type => String
  field :permalink, :type => String
  field :use_case_url, :type => String
  field :tagline, :type => String
  field :call_to_action, :type => String
  field :next_step_text, :type => String
  field :next_step_url, :type => String
  field :meta_title, :type => String
  field :meta_description, :type => String
  field :meta_keywords, :type => String
  field :is_visible, :type => Boolean, :default => false

  validates :title, :presence => true,
    :uniqueness => true
  validates :permalink, :presence => true,
    :uniqueness => { :case_sensitive => false },
    :format => {
      :with => %r{\A[a-z0-9][a-z0-9_\-]*\Z},
      :message => 'must only contain alphanumeric characters, dashes or underscores'
    }
  validates :use_case_url, :presence => true, :format => {
    :with => URI::regexp(%w(http https)),
    :message => 'is an invalid URL'
  }
  validates :tagline, :presence => true
  validates :call_to_action, :presence => true
  validates :next_step_text, :presence => true
  validates :next_step_url, :presence => true, :format => {
    :with => URI::regexp(%w(http https)),
    :message => 'is an invalid URL'
  }
  validates :meta_title, :presence => true
  validates :meta_description, :presence => true
  validates :meta_keywords, :presence => true
  validates :is_visible, :inclusion => {
    :in => [false],
    :unless => :acceptable_number_of_images_and_steps?,
    :message => 'cannot be visible until image and step requirements are met'
  }
  default_scope order_by(:title.asc)

  def self.by_permalink(permalink)
    where(:permalink => permalink).first
  end

  def acceptable_number_of_steps?
    steps.length == 3
  end

  def acceptable_number_of_images_and_steps?
    images.length > 0 && acceptable_number_of_steps?
  end
end

app/models/landing_page/landing_page_image.rb
class LandingPageImage
  include Mongoid::Document
  include Mongoid::Timestamps
  include HasVisibility
  include Mongoid::Orderable

  orderable

  embedded_in :landing_page, :inverse_of => :images

  field :caption, :type => String
  field :original_uid, :type => String
  field :large_uid, :type => String
  field :medium_uid, :type => String
  field :small_uid, :type => String
  image_accessor :original do
    copy_to(:large) {|a| a.thumb('1600x800#') }
    copy_to(:medium) {|a| a.thumb('800x400#') }
    copy_to(:small) {|a| a.thumb('320x160#') }
  end
  image_accessor :large
  image_accessor :medium
  image_accessor :small

  field :image_uid, :type => String
  image_accessor :image

  default_scope order_by(:position.asc)

  validates_presence_of :caption, :original

  default_scope order_by(:position.asc)
end

app/models/landing_page/landing_page_step.rb
class LandingPageStep
  include Mongoid::Document
  include Mongoid::Timestamps
  include HasVisibility
  include Mongoid::Orderable

  orderable

  embedded_in :landing_page, :inverse_of => :steps

  field :title, :type => String
  field :description, :type => String
  field :image_uid, :type => String
  field :original_uid, :type => String
  image_accessor :original do
    copy_to(:image) {|a| a.thumb('500x380#') }
  end
  image_accessor :image

  validates_presence_of :title, :description, :original

  default_scope order_by(:position.asc)

  def number
    self.landing_page.steps.index(self) + 1
  end
end

app/controllers/admin/landing_pages_controller.rb
class Admin::LandingPagesController < Admin::BaseController
end

app/controllers/landing_pages_controller.rb
class LandingPagesController < ApplicationController
  helper_method :page

  def show
    redirect_to root_url unless landing_page?
  end

  protected

  def landing_page
    @landing_page ||= LandingPage.visible.by_permalink(params[:id])
  end

  def landing_page?
    landing_page
  end

  def page
    @page ||= LandingPagePresenter.new(landing_page, view_context)
  end

  def default_meta_tags
    super.merge!({
      :site => page.meta_title,
      :title => nil,
      :description => page.meta_description,
      :keywords => page.meta_keywords
    })
  end
end

app/views/admin/landing_pages/_docs.html.erb
<div class="modal-header">
  <a class="close" data-dismiss="modal">×</a>
  <h3><%= plural_resource %> CMT</h3>
</div>
<div class="modal-body">
  <p>Here are a few things to know about this CMT:</p>
  <ul>
    <li>The title, use_case_url, tagline, step_one, step_two, step_three, call_to_action, next_step_text, and next_step_url attributes are required.</li>
    <li>The visibility of a <%= singular_resource %> on the front-end of the website can be controlled via the hide/show buttons in the list view.</li>
    <li>Sorting is controlled via drag-and-drop in the list view.</li>
  </ul>
</div>

app/views/admin/landing_pages/_form.html.erb
<%= form.input :title, :input_html => { :class => 'span4' } %>
<%= form.input :permalink, :input_html => { :class => 'span4' } %>
<%= form.input :use_case_url, :input_html => { :class => 'span4' } %>
<%= form.input :tagline, :as => :text %>
<%= form.input :call_to_action, :as => :text %>

<fieldset>
  <legend>Next Step</legend>
  <%= form.input :next_step_text, :label => "Text'", :input_html => { :class => 'span4' } %>
  <%= form.input :next_step_url, :label => "URL", :input_html => { :class => 'span4' } %>
</fieldset>

<fieldset>
  <legend>Meta</legend>
  <%= form.input :meta_title, :label => "Title", :input_html => { :class => 'span8' } %>
  <%= form.input :meta_description, :label => "Description", :input_html => { :class => 'span8' } %>
  <%= form.input :meta_keywords, :label => "Keywords", :hint => "A comma-separated list", :input_html => { :class => 'span8' } %>
</fieldset>

<%= form.input :is_visible, :as => :radio_buttons, :label => "Visible?", :hint => 'A landing page cannot be made visible until image and step requirements are met. If this is a new landing page, you\'ll be able to add images and steps after you save this form.', :collection => [["Yes", true], ["No", false]] %>

app/views/admin/landing_pages/edit.html.erb
<div class="row">
  <div class="span12">
    <%= ariane.render %>
  </div>
</div>

<% unless resource.acceptable_number_of_images_and_steps? %>
<div class="alert alert-block push">
  <a class="close" data-dismiss="alert">×</a>
  <h4 class="alert-heading">Important!</h4>
  In order for a landing page to display on the site, it must have three steps and at least one image.
</div>
<% end %>

<div class="btn-group push">
  <%= link_to(admin_landing_page_images_path(resource), :class => "btn") do %>
    Manage Images
    <span class="badge"><%= resource.images.length %></span>
  <% end %>
  <%= link_to(admin_landing_page_steps_path(resource), :class => "btn") do %>
    Manage Steps
    <span class="badge"><%= resource.steps.length %></span>
  <% end %>
</div>
<br>

<%= simple_form_for resource, :url => resource_path(resource), :html => { :multipart => true } do |form| %>
  <%= render :partial => 'form', :locals => { :form => form } %>
  <%= form.error :base %>
  <div class="form-actions">
    <button type="submit" class="btn btn-primary" data-loading-text="saving...">Save changes</button>
    <%= link_to("Cancel", collection_path, :class => 'btn') %>
  </div>
<% end %>

app/views/admin/landing_pages/index.html.erb
<%= render :partial => "/admin/shared/create_and_paginate" %>

<%= simple_table_for collection, :with => "#{resource_class}Table", :present_with => CrushTablePresenter %>

<%= paginate collection %>

app/views/admin/landing_pages/new.html.erb
<%= render 'admin/shared/new' %>