config/routes.rb
require 'sidekiq/web'

Chippd::Application.routes.draw do
  get "newsletter/index"

  get "newsletter/thanks"

  constraints(ApiConstraint) do
    scope :module => "api" do
      namespace :v1, :path => '1', :defaults => { :format => 'json' } do
        resource :customer, :only => [:create] do
          post 'sign_in'
        end
        get 'pages', :to => 'pages#index'
        get 'pages/not_found', :to => 'pages#not_found', :format => 'html'
        get 'pages/:key', :as => :page, :to => 'pages#show', :format => 'html'
        post 'pages/:key/leave', :as => :leave_page, :to => 'pages#leave'
        get 'pages/*junk', :to => 'pages#not_found', :format => 'html'
      end

      namespace :v2, :path => '2', :defaults => { :format => 'json' } do
        resource :customer, :only => [:create] do
          post 'sign_in'
        end
        get 'pages', :to => 'pages#index'
        get 'pages/not_found', :to => 'pages#not_found', :format => 'html'
        get 'pages/:key', :as => :page, :to => 'pages#show', :format => 'html'
        post 'pages/:key/leave', :as => :leave_page, :to => 'pages#leave'
        get 'pages/*junk', :to => 'pages#not_found', :format => 'html'
        resources :aws_signatures, only: :create, path: 'signatures'
        resources :mobile_playlists, only: :show, path: 'playlists'
      end
    end
  end

  devise_for :customers, :controllers => { :registrations => "customers/registrations", :sessions => "customers/sessions", :passwords => "customers/passwords" }
  devise_for :admins

  authenticate :admin do
    mount Sidekiq::Web => '/admin/sidekiq'
  end

  namespace :admin do
    resources :pages
    resources :product_collections, :except => [:show] do
      post 'sort', :on => :collection
      put 'toggle_visibility', :on => :member

      resources :products do
        post 'sort', :on => :collection
        put 'toggle_visibility', :on => :member
      end
    end

    resources :products, :only => nil do
      resources :images, :controller => "product_images" do
        post 'sort', :on => :collection
        put 'toggle_visibility', :on => :member
      end
    end

    resources :page_templates, :except => [:show] do
      post 'sort', :on => :collection
      put 'toggle_visibility', :on => :member
      resources :page_template_widgets, :path => 'widgets', :except => [:show] do
        post 'sort', :on => :collection
        put 'toggle_visibility', :on => :member
      end
    end
    resources :batches, :except => [:edit, :update, :destroy]
    resources :landing_pages do
      put 'toggle_visibility', :on => :member
      resources :steps, :controller => 'landing_page_steps' do
        post 'sort', :on => :collection
        put 'toggle_visibility', :on => :member
      end
      resources :images, :controller => 'landing_page_images' do
        post 'sort', :on => :collection
        put 'toggle_visibility', :on => :member
      end
    end
    root :to => "base#home"
    post 'markdown_preview', :to => "base#markdown_preview"

    resources :contact_requests, :only => [:index, :show, :destroy]
    resources :dollar_amount_discounts, :only => [:new, :edit, :create, :update]
    resources :percentage_discounts, :only => [:new, :edit, :create, :update]
    resources :discounts, :only => [:index, :toggle_visibility, :destroy] do
      put 'toggle_visibility', :on => :member
    end

    resources :shipping_options do
      post 'sort', :on => :collection
      put 'toggle_visibility', :on => :member
    end

    resources :chippd_product_types, :path => 'settings' do
      post 'sort', :on => :collection
      put 'toggle_visibility', :on => :member
    end

    resources :faqs do
      post 'sort', :on => :collection
      put 'toggle_visibility', :on => :member
    end

    resources :press_releases do
      post 'sort', :on => :collection
      put 'toggle_visibility', :on => :member
    end

    resources :contents

    resources :orders, :only => [:index, :edit, :update] do
      post 'search', :on => :collection
      get 'paid', :on => :collection
      get 'shipped', :on => :collection
      get 'canceled', :on => :collection
      put 'ship', :on => :member
      put 'cancel', :on => :member
      get 'invoice', :on => :member
    end

    resources :customers, :only => [:index, :show] do
      get 'line_items', :on => :collection
      get 'confirm', :on => :member
    end
  end

  namespace :store do
    root :to => "product_collections#index"
    get ':product_collection_id/products', :to => "products#index", :as => :products_by_product_collection
    get ':product_collection_id/:page_template_id/products', :to => "products#index_by_page_template", :as => :products_by_product_collection_and_page_template
    resources :products, :only => [:show] do
      resources :preorders, :only => [:create]
    end
    resource :order, :only => [:show, :update] do
      get 'cart', :as => :cart_for
      put 'cart/save', :action => 'save_cart', :as => :save_cart_for
      get 'customer_information', :as => :customer_information_for
      put 'customer_information/save', :action => 'save_customer_information', :as => :save_customer_information_for
      get 'review'
      put 'complete'
      get 'thank_you', :as => :thank_you_for_your
      get 'error', :as => :error_on_your
      resources :line_items, :only => [:create, :destroy]
      resource :applied_discount, :only => :destroy
    end
  end

  namespace :my_chippd, :path => 'my-chippd' do
    root :to => "base#index"
    resource :profile, :only => [:edit, :update, :destroy]
    resources :redemptions, :path => 'redeem', :only => [:index, :create] do
      get 'verify', :on => :collection
    end
    resources :pages, :only => [:index, :show, :edit, :update] do
      get 'chooser', :on => :collection, :as => :chooser_for
      put 'add_to_or_create', :on => :collection
      get 'example', :on => :collection
      post 'notify', :on => :member

      resources :memberships, :only => [:toggle_access] do
        put 'toggle_access', :on => :member
      end
      resources :auctions, :only => [] do
        post 'bid',   :on => :member
        get  'close', :on => :member
        get  'show',  :on => :collection
      end

      resources :sections do
        configatron.pages.valid_section_types.each do |section_type|
          get [:new, section_type].join('-'), :action => [:new, section_type].join('_'), :on => :collection, :as => [:new, section_type, :for].join('_')
        end
        delete 'reset', :on => :collection
        post 'sort', :on => :collection
        get 'download_vcard', :on => :member
        get 'content', :on => :member
        put 'toggle_visibility', :on => :member
      end
    end
  end
  post '/pusher/auth', to: 'my_chippd/base#pusher_auth'

  resources :rsvps, :only => [] do
    resources :responses, :only => [:index, :create, :update, :destroy], :controller => 'my_chippd/rsvp_responses'
  end

  get '/about-us', :to => "pages#about_us", :as => :about_us
  get '/go', :to => "pages#go"
  get '/how-it-works', :to => "pages#how_it_works", :as => :how_it_works
  get '/faq', :to => "pages#faq"
  get '/retailers', :to => "pages#retailers"
  get '/terms-of-service', :to => "pages#terms_of_service", :as => :terms_of_service
  get '/privacy-policy', :to => "pages#privacy_policy", :as => :privacy_policy
  get '/media-room', :to => "pages#media_room", :as => :media_room

  get '/newsletter', :to => "newsletter#index"
  get '/newsletter/thanks', :to => "newsletter#thanks"

  get '/widgets/baby', :to => "widgets#baby"
  get '/widgets/wedding', :to => "widgets#wedding"


  get '/contact-us', :to => "contact_requests#new", :as => :contact_us
  get '/contact-us/thank-you', :to => "contact_requests#thank_you", :as => :contact_request_thank_you
  resources :contact_requests, :only => [:new, :create], :path => 'contact-requests'

  get '/redeem', to: redirect('/activate')
  get '/activate', :to => "pages#redeem_tracking", as: 'redeem'

  resources :press_releases, :only => [:index, :show], :path => 'press'

  configatron.example_pages.each do |path, id|
    get "/examples/#{path.to_s.dasherize}", :to => "examples#show", :as => "#{path}_example", :id => id, :key => path
  end
  get "/ebolaandbeyond", :to => "my_chippd/auctions#show", :page_id => "54d274234c06fcc008000001"
  get "/ppaiexpoeast", :to => "examples#show", :page_id => "54f68261ee2cb7efa9000002", :as => "ppaiexpoeast_example", :id => '54f68261ee2cb7efa9000002', :key => 'ppaiexpoeast'
  get "/intro", :to => "examples#show", :page_id => "54f684a4ee2cb7efa9000003", :as => "intro_example", :id => '54f684a4ee2cb7efa9000003', :key => 'ppaiexpoeast'
  # get "/omaranddina", :to => "my_chippd/auctions#show", :page_id => "54eeb4b63672bcb7c0000028"
  get "/omaranddina", :to => "examples#show", :page_id => "5523084ff400bf85be000001", :as => "omaranddina_example", :id => '5523084ff400bf85be000001', :key => 'omaranddina'

  root :to => "pages#home"
  get '/:id', :to => 'landing_pages#show'
end

app/models/order/address.rb
class Address
  include Mongoid::Document
  embedded_in :order

  field :first_name, :type => String
  field :last_name, :type => String
  field :address_1, :type => String
  field :address_2, :type => String
  field :city, :type => String
  field :state, :type => String
  field :postal_code, :type => String
  field :country, :type => String, :default => 'United States'

  validates :first_name, :presence => true
  validates :last_name, :presence => true
  validates :address_1, :presence => true
  validates :city, :presence => true
  validates :state, :presence => true
  validates :postal_code, :presence => true
  validates :country, :presence => true
end

app/models/order/applied_discount.rb
class AppliedDiscount
  include Mongoid::Document
  embedded_in :order
  belongs_to :discount

  field :amount_in_cents, :type => Integer, :default => 0
  field :name, :type => String
  field :code, :type => String

  validates :discount, :presence => true
  validates :code, :presence => true

  set_callback(:create, :before) do |document|
    document.name = document.discount.name
    document.amount = document.discount.apply(document.order.subtotal)
  end

  # Public: Gets the amount of a product.
  #
  # Returns a Money object based on the value of #amount_in_cents and #currency.
  def amount
    Money.new(self.amount_in_cents, configatron.default_currency)
  end

  # Public: Sets the amount of a product.
  #
  # val - A String or Numeric representation of the product's amount.
  #
  # Returns the value of #amount_in_cents.
  def amount=(val)
    self.amount_in_cents = val.to_money.cents
  end
end

app/models/order/line_item.rb
class LineItem
  include Mongoid::Document

  embedded_in :order

  belongs_to :product
  belongs_to :product_collection
  belongs_to :chippd_product_type

  field :product_name, :type => String
  field :chippd_product_type_name, :type => String
  field :product_collection_name, :type => String
  field :price_each_in_cents, :type => Integer, :default => 0
  field :key, :type => String
  field :quantity, :type => Integer, :default => 1
  field :options, :type => Array, :default => []
  field :codes_array, :type => Array, :default => []

  delegate :greeting_card?, :to => :product

  validates :price_each_in_cents, :presence => true,
    :numericality => true
  validates :quantity, :presence => true,
    :numericality => true

  set_callback(:save, :before) do |document|
    document.set_association_names
  end

  set_callback(:save, :after) do |document|
    document.order.recalculate_subtotal!
  end

  set_callback(:destroy, :after) do |document|
    document.order.recalculate_subtotal!
  end

  def update_quantity_by(_quantity)
    self.inc(:quantity, _quantity.to_i)
  end

  def codes
    self.codes_array.join(',')
  end

  def codes=(_codes)
    self.codes_array = _codes.split(',').collect(&:strip).collect(&:upcase).reject(&:blank?)
  end

  # Public: Build a LineItem object from a Product's attributes.
  #
  # product - A Product object to build the LineItem from.
  #
  # Returns a LineItem object.
  def self.build_from_product(product)
    line_item = LineItem.new
    line_item.product = product
    line_item.chippd_product_type = product.default_chippd_product_type
    line_item
  end

  # Public: Calculate total price of line item
  #
  # Returns a Money object based on the value of #price_each_in_cents and #currency.
  def price
    self.price_each * self.quantity
  end

  # Public: Gets the price_each of a product.
  #
  # Returns a Money object based on the value of #price_each_in_cents and #currency.
  def price_each
    Money.new(self.price_each_in_cents, configatron.default_currency)
  end

  # Public: Sets the price_each of a product.
  #
  # val - A String or Numeric representation of the product's price_each.
  #
  # Returns the value of #price_each_in_cents.
  def price_each=(val)
    self.price_each_in_cents = val.to_money.cents
  end

  def image
    self.product.default_image
  end

  def page_template_id
    self.product.page_template_id
  end

protected

  def set_association_names
    self.chippd_product_type_name = self.chippd_product_type.name
    self.product_name = self.product.name
    self.product_collection = self.product.product_collection
    self.product_collection_name = self.product_collection.name
  end
end

app/models/order/payment_card.rb
class PaymentCard
  include Mongoid::Document
  embedded_in :order

  field :brand, :type => String
  field :last4, :type => String
  field :exp_month, :type => String
  field :exp_year, :type => String
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < Admin::BaseController
  helper_method :order_counts, :presented_order

  def index
    redirect_to paid_admin_orders_url
  end

  def search
    if params[:number].blank?
      redirect_to(paid_admin_orders_url, :alert => "Please enter an order number before you search.") and return
    end

    order = Order.where(:number => params[:number].upcase).first

    if order
      redirect_to(edit_admin_order_url(order))
    else
      redirect_to(paid_admin_orders_url, :alert => "An order with that number could not be found.")
    end
  end

  def paid
    @collection = Order.paid.all
    render 'index'
  end

  def shipped
    @collection = Order.shipped.all
    render 'index'
  end

  def canceled
    @collection = Order.canceled.all
    render 'index'
  end

  def ship
    resource.ship!
    redirect_to edit_admin_order_url(resource)
  end

  def cancel
    resource.cancel!
    redirect_to edit_admin_order_url(resource)
  end

  def invoice
    render :layout => false
  end

  protected

  def order_counts
    {
      :paid => Order.paid.count,
      :shipped => Order.shipped.count,
      :canceled => Order.canceled.count
    }
  end

  def presented_order
    @presented_order ||= OrderPresenter.new(resource, view_context)
  end

  def setup_edit_breadcrumb
    ariane.add "<code>#{resource.number}</code>", edit_resource_path(resource)
  end
end

app/controllers/store/orders_controller.rb
class Store::OrdersController < Store::BaseController
  before_filter :redirect_unless_current_order, :except => [:error]
  before_filter :set_order_instance, :except => [:thank_you, :error]
  before_filter :authenticate_customer!, :except => [:show, :cart, :save_cart]
  layout 'simple', :only => [:thank_you, :error]

  def show
    redirect_to cart_for_store_order_url
  end

  def cart
  end

  def save_cart
    if @order.save_cart(params[:order])
      redirect_to cart_for_store_order_url
    else
      render 'cart'
    end
  end

  def customer_information
    @order.pair_with_customer!(current_customer)
    @order.initialize_customer_information
    prepare_shipping_options
  end

  def save_customer_information
    if @order.save_customer_information(params[:order], current_customer, params[:stripeToken])
      redirect_to review_store_order_url
    else
      prepare_shipping_options
      render 'customer_information'
    end
  end

  def review
  end

  def complete
    if @order.complete!(params[:order], session[:page_id])
      redirect_to thank_you_for_your_store_order_url
    else
      render 'review'
    end
  end

  def thank_you
    session[:order_id] = nil
    session[:chippd_product_type_id] = nil
    if session[:page_id]
      @for_existing_page = true
      session[:page_id] = nil
    end
  end

  def error
  end

  protected

  def redirect_unless_current_order
    redirect_to store_root_url unless current_order?
  end

  def set_order_instance
    @order = current_order.order
  end

  def prepare_shipping_options
    @shipping_options = ShippingOptionQuery.call(@order).collect { |so| [so.name, so.key]}
    @default_shipping_option = @order.shipping_option.present? ? @order.shipping_option : @shipping_options.first[1]
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
  def unless_for_existing_page(&block)
    @for_existing_page ? render('for_existing_page') : capture(&block)
  end
end

app/views/admin/orders/_timestamp.html.erb
<% if order.paid? %>
  <%= order.purchased_at.stamp(configatron.datetime_formats.default) %>
<% elsif order.shipped? %>
  <%= order.shipped_at.stamp(configatron.datetime_formats.default) %>
<% elsif order.canceled? %>
  <%= order.canceled_at.stamp(configatron.datetime_formats.default) %>
<% else %>
<% end %>

app/views/admin/orders/edit.html.erb
<%= ariane.render %>

<div class="row">
  <div class="span8">
    <div class="btn-group push">
      <% unless presented_order.shipped? || presented_order.canceled? %>
        <%= link_to(ship_admin_order_path(presented_order), :method => :put, :class => "btn btn-primary", :confirm => "Are you sure you want to ship this order?") do %>
        Ship
        <% end %>
        <%= link_to(cancel_admin_order_path(presented_order), :method => :put, :class => "btn btn-primary", :confirm => "Are you sure you want to cancel this order?") do %>
        Cancel
        <% end %>
        <%= link_to(invoice_admin_order_path(presented_order), :method => :get, :class => "btn btn-primary") do %>
        View Packing Slip
        <% end %>
      <% end %>
    </div>
    &nbsp;
  </div>
  <div class="span4">
    <p class="pull-right order-status">
      <strong>Status</strong>: <span class="badge badge-<%= presented_order.state_badge_class %>"><%= presented_order.state.upcase %></span><br>
      <strong>Date</strong>: <%= render :partial => 'timestamp', :locals => { :order => presented_order } %>
    </p>
  </div>
</div>

<h3 class="push">Totals</h3>
<div class="well">
  <ul id="order-total">
    <li class="subtotal">Subtotal: <em><%= presented_order.formatted_subtotal %></em></li>
    <% if presented_order.has_discount? %>
    <li class="discount">Discount: <em>-<%= presented_order.formatted_discount_amount %></em></li>
    <% end %>
    <li class="shipping">Shipping: <em><%= presented_order.formatted_shipping_cost %></em></li>
    <li class="tax">Sales Tax: <em><%= presented_order.formatted_sales_tax %></em></li>
    <li class="total">Grand Total: <em><%= presented_order.formatted_total %></em></li>
  </ul>
</div>

<h3 class="push">Cart</h3>
<%= simple_form_for resource, :url => resource_path(resource), :html => { :multipart => true } do |form| %>
<table class="table table-striped">
  <thead>
    <tr>
      <th class="item-name">Item</th>
      <th class="quantity"><abbr title="Quantity">Qty.</abbr></th>
      <th class="total">Total</th>
      <th class="codes">QR Codes</th>
    </tr>
  </thead>

  <tbody>
    <%= form.simple_fields_for :line_items do |line_item_form| %>
      <% line_item = LineItemPresenter.new(line_item_form.object, self) %>
    <tr>
      <td class="item-name"><%= line_item.link_to_product %> <%= line_item.options %></td>
      <td class="quantity"><%= line_item.quantity %></td>
      <td class="total"><%= line_item.price %></td>
      <td>
          <%= line_item_form.input :codes, :required => false, :label => false %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>
<div class="form-actions">
  <button type="submit" class="btn btn-primary" data-loading-text="saving...">Save changes</button>
</div>
<% end %>
<h3 class="push">Address &amp; Shipping Information</h3>
<div class="well">
  <h4>Billing Address</h4>
  <%= render :partial => '/store/orders/address_vcard', :locals => { :address => AddressPresenter.new(presented_order.billing_address, self), :editable => false } %>
  <hr>
  <h4>Shipping Address</h4>
  <%= render :partial => '/store/orders/address_vcard', :locals => { :address => AddressPresenter.new(presented_order.shipping_address, self), :editable => false } %>
  <hr>
  <h4>Shipping Option</h4>
  <p><%= presented_order.shipping_option %></p>
  <%= PackingPresenter.new(resource, self).info %>
  <hr>
  <h4>Tracking Information</h4>
  <p>Neither of these fields are required, but if they're present, they'll be included in the shipping email that the customer receives. Make sure you fill these fields out and save them before marking the order as shipped.</p>
  <%= simple_form_for resource, :url => resource_path(resource), :html => { :multipart => true } do |form| %>
    <%= form.input :estimated_delivery_date, :required => false %>
    <%= form.input :tracking_number, :required => false %>
    <div class="form-actions">
      <button type="submit" class="btn btn-primary" data-loading-text="saving...">Save changes</button>
    </div>
  <% end %>
</div>

<h3 class="push">Gift Information</h3>
<table class="table table-striped">
  <tr>
    <th>Gift?</th>
    <td><%= presented_order.is_gift %></td>
  </tr>
  <tr>
    <th>Gift Code</th>
    <td><%= presented_order.gift_code %></td>
  </tr>
  <tr>
    <th>Recipient Email</th>
    <td><%= presented_order.gift_recipient_email %></td>
  </tr>
  <tr>
    <th>Message</th>
    <td><%= presented_order.gift_recipient_message %></td>
  </tr>
  <tr>
    <th>Gift Code Redeemed?</th>
    <td><%= presented_order.gift_code_redeemed %></td>
  </tr>
  <tr>
    <th>Gift Code Redeemed By</th>
    <td><%= presented_order.gift_code_redeemed_by %></td>
  </tr>
</table>

<h3 class="push">Payment Details</h3>
<div class="well">
  <%= render :partial => '/store/orders/payment_card', :locals => { :payment_card => PaymentCardPresenter.new(presented_order.payment_card, self) } %>
</div>

app/views/admin/orders/index.html.erb
<div class="row">
  <div class="span4">
    <div class="btn-group push">
      <%= link_to(paid_admin_orders_path, :class => "btn#{is_active?(controller.action_name, 'paid', ' active')}") do %>
        Paid <span class="badge"><%= order_counts[:paid] %></span>
      <% end %>
      <%= link_to(shipped_admin_orders_path, :class => "btn#{is_active?(controller.action_name, 'shipped', ' active')}") do %>
        Shipped <span class="badge"><%= order_counts[:shipped] %></span>
      <% end %>
      <%= link_to(canceled_admin_orders_path, :class => "btn#{is_active?(controller.action_name, 'canceled', ' active')}") do %>
        Canceled <span class="badge"><%= order_counts[:canceled] %></span>
      <% end %>
    </div>
  </div>
  <div class="span8">
    <%= form_tag search_admin_orders_path, :method => :post, :class => 'form-search pull-right' do %>
    <%= text_field_tag 'number', '', :placeholder => 'search by number', :class => 'span2 search-query' %>
    <button type="submit" class="btn btn-info" data-loading-text="saving...">Search</button>
    <% end %>
  </div>
</div>

<%= simple_table_for collection, :with => "#{resource_class}Table", :present_with => CrushTablePresenter %>

app/views/admin/orders/invoice.html.erb
<html>
<head>
  <title>Chipp'd | Invoice <%= presented_order.number %></title>

  <style>
    * {
      margin: 0;
      padding: 0;
    }

    body {
      font-size: 100%;
      color: #411750;
      font-family: sans-serif;
    }

    ul {
      list-style-type: none;
    }

    p, td, th, li {
      font-size: 12px;
      line-height: 17px;
    }

    a {
      color: #411750;
      text-decoration: none;
    }

    table {
      width: 100%;
      border: none;
      border-collapse: collapse;
      margin-bottom: 30px;
    }

    th, td {
      padding: 10px;
      text-align: left;
      vertical-align: top;
    }

    th {
      border-bottom: 7px solid #411750;
      white-space: nowrap;
    }

    .container {
      padding: 20px 10px;
    }

    header[role='masthead'] {
      overflow: hidden;
      text-align: center;
      margin-bottom: 40px;
      padding: 0 10px 40px 10px;
      border-bottom: 7px solid #411750;
    }
    header[role='masthead'] .text {
      display: inline-block;
      float: left;
      width: 170px;
      height: auto;
      margin: 40px 0 0 0;
    }
    header[role='masthead'] .logo {
       height: 100px;
       width: auto;
    }
    header[role='masthead'] ul {
      text-align: left;
      float: right;
      margin-top: 25px;
    }
    h1 {
      font-size: 1.5em;
      padding-left: 10px;
      margin-bottom: 10px;
    }
    .shipping {
      margin-bottom: 0;
    }

    .adr .street-address {
      display: block;
    }

    .info {
      padding: 0 0 20px 10px;
    }

    .items {
    }

    .items td {
      border-bottom: 1px solid #888;
    }

    .items .totals td {
      border: none;
    }

    .items td.payment {
      text-align: right;
      vertical-align: bottom;
    }

    .items td.labels li {
      text-align: right;
      font-weight: bold;
    }

    footer {
      width: 75%;
      margin: 60px auto 0;
      text-align: center;
    }

    footer p {
      padding: 20px 0 0 0;
    }

  </style>

</head>
<body>

  <div class="container">

    <header role="masthead">
        <%= image_tag('logo-wordmark.png', :class => 'text', :alt => "Chipp'd — Made in NYC") %>
        <%= image_tag('logo-nyc.png', :class => 'logo', :alt => "Chipp'd — Made in NYC") %>
        <ul>
          <li>Chipp'd Ltd.</li>
          <li>175 Varick Street</li>
          <li>New York, NY 10014</li>
          <li><a href="mailto:orders@chippd.com">orders@chippd.com</a></li>
        </ul>
    </header>

    <h1>Customer Invoice</h1>

    <p class="info">Order No. <%= presented_order.number %><br/>You placed this order on <%= presented_order.purchased_at.stamp(configatron.date_formats.invoice) %> and paid with your <%= presented_order.payment_card.brand %> ending in <%= presented_order.payment_card.last4 %>.</p>

    <table class="shipping">
      <tr>
        <th>bill to</th>
        <th>ship to</th>
      </tr>
      <tr>
        <td>
          <%= render :partial => '/store/orders/address_vcard', :locals => { :address => AddressPresenter.new(presented_order.billing_address, self), :editable => false } %>
        </td>
        <td>
          <%= render :partial => '/store/orders/address_vcard', :locals => { :address => AddressPresenter.new(presented_order.shipping_address, self), :editable => false } %>
        </td>
      </tr>
    </table>

    <table class="items">
      <thead>
        <tr>
          <th>qty</th>
          <th>item</th>
          <th>price</th>
          <th>total</th>
        </tr>
      </thead>
      <tbody>
        <% presented_order.line_items.each do |line_item| %>
        <tr>
          <td><%= line_item.quantity %></td>
          <td><%= line_item.link_to_product %><br/><%= line_item.options %></td>
          <td><%= line_item.price_each %></td>
          <td><%= line_item.price %></td>
        </tr>
        <% end %>
      </tbody>
      <tfoot>
        <tr class="totals">
          <td colspan="2"></td>
          <td class="labels">
            <ul id="order-total">
              <li class="subtotal">Subtotal:</li>
<% if presented_order.has_discount? %>
              <li class="discount">Discount:</li>
<% end %>
              <li class="shipping">Shipping (<%= presented_order.shipping_option %>):</li>
              <li class="tax">Sales Tax:</li>
              <li class="total">Grand Total:</li>
            </ul>
          </td>
          <td>
            <ul id="order-total">
              <li class="subtotal"><%= presented_order.formatted_subtotal %></li>
<% if presented_order.has_discount? %>
              <li class="discount">-<%= presented_order.formatted_discount_amount %></li>
<% end %>
              <li class="shipping"><%= presented_order.formatted_shipping_cost %></li>
              <li class="tax"><%= presented_order.formatted_sales_tax %></li>
              <li class="total"><%= presented_order.formatted_total %></li>
            </ul>
          </td>
        </tr>
      </tfoot>
    </table>

    <footer>
      <h4>Thank you for ordering from Chipp’d!  We hope you enjoy your products.  Now that we've connected, don’t be a stranger!</h4>
      <p><strong>Need to return something?</strong> Return your product within 10 days of receipt for a full refund. No questions asked. To learn more, visit chippd.com.</p>
    </footer>
  </div>

</body>
</html>